#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            0
bspc config window_gap              25

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#FFA066
bspc config focused_border_color    \#957FB8
bspc config active_border_color     \#1F1F28
bspc config normal_border_color     \#1F1F28

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

feh --bg-fill --randomize ~/Pictures/fav/* &
pidof eww && killall eww
$HOME/.software/eww/target/release/eww open bar &
pidof picom || pkill picom
picom -f --experimental-backends &
xsetroot -cursor_name left_ptr
setxkbmap -option "ctrl:swapcaps"
pidof dunst && pkill dunst
dunst &

