#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            0
bspc config window_gap              25

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#fe8019
bspc config focused_border_color    \#8ec07c
bspc config active_border_color     \#1d2021
bspc config normal_border_color     \#1d2021

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# feh --bg-fill ~/Pictures/gruvbox/gruvbox-wallpapers/wallpapers/irl/sunforest.jpg &
feh --bg-fill ~/Pictures/wallpapers/gruvy.jpg &
pidof eww && killall eww
$HOME/.software/eww/target/release/eww open bar &
pidof picom || pkill picom
picom -f --experimental-backends &
xsetroot -cursor_name left_ptr
setxkbmap -option "ctrl:swapcaps"
# pidof dunst && pkill dunst
# dunst &

